# Generated by Django 4.2.13 on 2024-08-21 08:05

from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=products.models.date_time)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
