# Generated by Django 4.2.13 on 2024-08-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Count',
            new_name='Product_count',
        ),
    ]
