# Generated by Django 4.2.13 on 2024-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_count_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='DEFAULT_TYPE', max_length=11),
        ),
    ]
